#!/usr/bin/env fish

function main
    log 'Update apt sources list'
    echo '
deb http://ftp.us.debian.org/debian unstable main contrib non-free
deb-src http://ftp.us.debian.org/debian unstable main contrib non-free' | sudo tee /etc/apt/sources.list

    log 'Upgrading debian to unstable'
    sudo apt-get update >/dev/null 2>&1
    sudo apt-get dist-upgrade --yes

    log 'Rebooting'
    sudo reboot
end

function log -a message
    echo \n"---------------- $message ----------------"\n
end

main
