#!/usr/bin/env fish

function main
    log 'Update apt sources list'
    echo '
deb http://ftp.us.debian.org/debian unstable main contrib non-free
deb-src http://ftp.us.debian.org/debian unstable main contrib non-free' | sudo tee /etc/apt/sources.list

    log 'Upgrading debian to unstable'
    sudo apt-get --quiet --yes update
    sudo apt-get --quiet --yes dist-upgrade

    log 'Rebooting'
    sudo reboot
end

function log -a message
    echo \n"--- $message ---"\n
end

main
