#!/usr/bin/env fish

if ! test -e ~/.bspwm_no_lock
  slock &
  touch ~/.bspwm_no_lock
end

setxkbmap -option ctrl:swapcaps
setxkbmap -option altwin:swap_alt_win
xset s off -dpms
xinput set-prop 'MSFT0001:00 04F3:317C Touchpad' 'libinput Tapping Enabled' 1
xinput set-prop 'MSFT0001:00 04F3:317C Touchpad' 'libinput Middle Emulation Enabled' 1

sxhkd &
picom -b

wmname LG3D

xfce4-screensaver &
~/.fehbg &

killall -q polybar barrier barrierc cbatticon pasystray
polybar m-bar &
cbatticon &
pasystray &
keepassxc &
barrier &

bspc monitor -d I II III IV V VI VII

bspc config border_width   2
bspc config window_gap     10
bspc config top_padding    -10

bspc config split_ratio         0.52
bspc config borderless_monocle  false
bspc config gapless_monocle     false

bspc config focused_border_color  '#92971a'

bspc rule -a 'firefox:*:Picture-in-Picture' state=floating sticky=on
bspc rule -a 'origin.exe:*' state=floating
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
