#!/usr/bin/fish

#if ! test -e ~/.bspwm_no_lock
#  slock &
#  touch ~/.bspwm_no_lock
#end

if test $DISPLAY = ":0"
    setxkbmap -option ctrl:swapcaps
    setxkbmap -option altwin:swap_alt_win
    xset s off -dpms
    xinput set-prop 'MSFT0001:00 04F3:317C Touchpad' 'libinput Tapping Enabled' 1
    xinput set-prop 'MSFT0001:00 04F3:317C Touchpad' 'libinput Middle Emulation Enabled' 1
end

sxhkd &

if test $DISPLAY = ":0"
    picom -b
else
    picom -b --backend xrender
end

#wmname LG3D

if test $DISPLAY = ":0"
    killall -q polybar pasystray barrier barrierc
    barrier &
    keepassxc &
    ~/.fehbg
else
    feh --no-fehbg --bg-scale '/home/m/sync/maelstrom.jpg'
end

polybar m-bar &
pasystray &

bspc monitor -d I II III IV V VI VII

bspc config border_width   2
bspc config window_gap     10
bspc config top_padding    -10

bspc config split_ratio         0.52
bspc config borderless_monocle  false
bspc config gapless_monocle     false

bspc config focused_border_color  '#CBC093'

bspc rule -a 'firefox:*:Picture-in-Picture' sticky=on
bspc rule -a 'origin.exe:*' state=floating
bspc rule -a 'osu!:*' state=floating rectangle=1600x1200
bspc rule -a 'mpv:*' rectangle=640x360+1270+710
bspc rule -a 'streamlink-twitch-gui:*' state=floating
# bspc rule -a 'mpv:*' sticky=on
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
